FROM node:18-slim

WORKDIR /usr/src/app

RUN apt-get update -y && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

RUN npm install -g prisma

COPY . .

RUN npm run build

EXPOSE 3333

ENTRYPOINT ["sh", "-c", "npx prisma migrate dev --name init && npm run prod"]
